---

- include: group.yml
  when: credentials_groups is defined
  
- include: user.yml
  when: credentials_users is defined

- name: install required packages
  apt: pkg={{item}} install_recommends=no
  with_items:
    - sudo
  when: ansible_lsb.id not in [ 'CentOS' ]

- name: copy ssh/sftp sudo wrapper
  copy:
    src: etc/ssh/sudo-wrapper
    dest: /etc/ssh/sudo-wrapper
    owner: root
    group: root
    mode: '0755'
  
- include: sudo.yml
  when:
    ansible_lsb.codename not in [ "sarge", "etch", "lenny" ] or
    ansible_lsb.id not in [ 'CentOS' ]

- include: sudo-old.yml
  when:
    ansible_lsb.codename in [ "sarge", "etch", "lenny" ] or
    ansible_lsb.id in [ 'CentOS' ]
