#!/bin/sh

# Copyright © 2015 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>

# Created: 2015-04-02
# Last changed: 2015-07-28 11:13:44

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

# Simple ssh wrapper that enables sudo when loggin using sftp.
#
# For this to work you should add the following option in your ssh
# authorized key:
#
#      command="/etc/ssh/sudo-wrapper"
#
# In addition you must also enable a passwordless sudo at least for
# sftp-server:
#
#    user ALL=(ALL) NOPASSWD:ALL
#    # This doen not seem to work properly
#    # user ALL=(ALL) NOPASSWD:/usr/lib/openssh/sftp-server
#



if test -z "${SSH_ORIGINAL_COMMAND}"; then
    case `uname -s` in
	OpenBSD)
	    if test -e /etc/profile; then
	       . /etc/profile
	    fi
	       ;;
    esac
    exec $SHELL
else
    case "$SSH_ORIGINAL_COMMAND" in
        /usr/lib/openssh/sftp-server) sudo -E $SSH_ORIGINAL_COMMAND ;;
        *)
            exec $SSH_ORIGINAL_COMMAND
            ;;
    esac
fi
